# .github/workflows/films-test.yml
name: Films API Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Atualizado para v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Atualizado para v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run films test
        run: npx jest swapi.test.js -t 'Films'
